project:
  type: website
  output-dir: docs 

website:
  title: "Mihnea POPA"
  navbar:
    left:
      - href: resume.qmd 
        text: Resume
      - href: projects.qmd  
        text: Projects
      - href: interview_questions.qmd  
        text: Interview Questions        
        
  search: false
format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true



